export const skills = [
  {id:"numbers",name:"الأعداد والعمليات",sort:1},
  {id:"algebra",name:"الجبر والأنماط",sort:2},
  {id:"proportion",name:"التناسب والاستدلال",sort:3},
  {id:"geometry",name:"الهندسة",sort:4},
  {id:"measurement",name:"القياس",sort:5},
  {id:"statistics",name:"الإحصاء والاحتمال",sort:6},
  {id:"pedagogy",name:"تعليم الرياضيات",sort:7}
];

export const questions = [
  {id:"q01",skill_id:"numbers",difficulty:"متوسط",is_diagnostic:true,priority:100,title:"مقارنة الكسور بالمعنى",question_text:"أي تفسير يبرهن أن ٧⁄١٢ أصغر من ٣⁄٤؟",options:["لأن ٧ أصغر من ٣","لأن ٣⁄٤ يساوي ٩⁄١٢، و٧⁄١٢ أصغر من ٩⁄١٢","لأن ١٢ أكبر من ٤","لأن الفرق بين البسطين يساوي ٤"],correct_index:1,explanation:"نوحّد المقام: ٣⁄٤ = ٩⁄١٢، ومن ثم ٧⁄١٢ < ٩⁄١٢.",trap:"مقارنة البسطين أو المقامين منفردين.",quick_method:"حوّل أحد الكسرين إلى مقام مشترك أو استخدم كسرًا مرجعيًا."},
  {id:"q02",skill_id:"pedagogy",difficulty:"متقدم",is_diagnostic:true,priority:99,title:"تحليل خطأ إعادة التجميع",question_text:"كتب متعلم: ٤٠٢ − ١٨٧ = ٣٨٥؛ لأنه طرح الرقم الأصغر من الأكبر في كل منزلة. ما التدخل التعليمي الأفضل أولًا؟",options:["إعطاؤه عشر مسائل مماثلة","مطالبته بحفظ خطوات الخوارزمية","تمثيل ٤٠٢ بقطع القيمة المنزلية وإعادة التجميع مع تقدير الناتج","السماح له باستخدام الآلة الحاسبة"],correct_index:2,explanation:"التمثيل بالقيمة المنزلية يكشف سبب إعادة التجميع، والتقدير يوضح أن الناتج غير معقول.",trap:"زيادة التدريب على خوارزمية لم يفهم معناها.",quick_method:"شخّص التصور الخاطئ ثم اختر تمثيلًا يكشفه."},
  {id:"q03",skill_id:"algebra",difficulty:"متوسط",is_diagnostic:true,priority:98,title:"قاعدة الحد النوني",question_text:"بدأ نمط عددي بالقيم: ٥، ٨، ١١، ١٤، … فما العبارة التي تمثل الحد النوني؟",options:["٣ن + ٢","٣ن + ٥","٥ن − ٢","ن + ٤"],correct_index:0,explanation:"الفرق ثابت ٣، وعند ن=١ يجب أن تكون القيمة ٥؛ لذا ٣ن+٢.",trap:"اعتبار الحد الأول هو الثابت مباشرة.",quick_method:"القاعدة = الفرق×ن + (الحد الأول−الفرق)."},
  {id:"q04",skill_id:"proportion",difficulty:"متوسط",is_diagnostic:true,priority:97,title:"تمييز التناسب الطردي",question_text:"أي مجموعة أزواج تمثل علاقة تناسب طردي ثابتة؟",options:["(٢،٦)، (٤،١٢)، (٦،١٨)","(٢،٦)، (٤،١٠)، (٦،١٤)","(١،٣)، (٢،٥)، (٣،٧)","(٢،٤)، (٣،٩)، (٤،١٦)"],correct_index:0,explanation:"النسبة ص⁄س ثابتة وتساوي ٣ في جميع الأزواج.",trap:"الاكتفاء بوجود نمط منتظم دون ثبات النسبة.",quick_method:"احسب ص÷س لكل زوج."},
  {id:"q05",skill_id:"geometry",difficulty:"متقدم",is_diagnostic:true,priority:96,title:"عامل القياس والمساحة",question_text:"إذا زاد طول ضلع مربع بنسبة ٥٠٪، فكم تكون نسبة الزيادة في مساحته؟",options:["٥٠٪","٧٥٪","١٠٠٪","١٢٥٪"],correct_index:3,explanation:"عامل القياس ١٫٥، وعامل المساحة ١٫٥²=٢٫٢٥؛ أي زيادة ١٢٥٪.",trap:"تطبيق نسبة الزيادة الخطية نفسها على المساحة.",quick_method:"المساحة تتغير بمربع عامل القياس."},
  {id:"q06",skill_id:"measurement",difficulty:"متقدم",is_diagnostic:true,priority:95,title:"استنتاج الأبعاد",question_text:"مستطيل مساحته ٤٨ وحدة مربعة ومحيطه ٢٨ وحدة. ما بعداه؟",options:["٤ و١٢","٦ و٨","٣ و١٦","٧ و٧"],correct_index:1,explanation:"مجموع البعدين ١٤ وحاصل ضربهما ٤٨، فيتحقق ذلك للعددين ٦ و٨.",trap:"استخدام شرط واحد فقط من المساحة أو المحيط.",quick_method:"ابحث عن عاملين للـ٤٨ مجموعهما نصف المحيط."},
  {id:"q07",skill_id:"statistics",difficulty:"متقدم",is_diagnostic:true,priority:94,title:"تصحيح المتوسط",question_text:"متوسط ٨ قيم يساوي ١٥. اكتُشف أن قيمة سُجلت ٩ بدلًا من ١٧. ما المتوسط الصحيح؟",options:["١٥","١٦","١٧","٢٣"],correct_index:1,explanation:"المجموع المسجل ١٢٠، نضيف فرق التصحيح ٨ فيصبح ١٢٨، ثم ١٢٨÷٨=١٦.",trap:"إضافة القيمة الصحيحة دون طرح القيمة الخاطئة.",quick_method:"صحح المجموع أولًا ثم اقسم."},
  {id:"q08",skill_id:"statistics",difficulty:"متقدم",is_diagnostic:true,priority:93,title:"احتمال دون إرجاع",question_text:"صندوق فيه ٣ كرات حمراء وكرتان زرقاوان. سُحبت كرتان دون إرجاع. ما احتمال أن تكونا زرقاوين؟",options:["١⁄٥","١⁄١٠","٢⁄٥","١⁄٤"],correct_index:1,explanation:"٢⁄٥ × ١⁄٤ = ١⁄١٠.",trap:"إبقاء المقام ٥ في السحب الثاني.",quick_method:"حدّث عدد العناصر بعد السحب الأول."},
  {id:"q09",skill_id:"numbers",difficulty:"متقدم",is_diagnostic:true,priority:92,title:"معنى قسمة الكسور",question_text:"أي تمثيل يوضح بصورة أفضل معنى ٢⁄٣ ÷ ١⁄٦؟",options:["وضع ٢⁄٣ على خط أعداد وعدّ المقاطع التي طول كل منها ١⁄٦","جمع ٢⁄٣ و١⁄٦","رسم ٢⁄٣ من ستة أشكال فقط","مقارنة المقامين دون تمثيل"],correct_index:0,explanation:"القسمة تسأل: كم جزءًا حجمه ١⁄٦ يوجد داخل ٢⁄٣؟ والجواب ٤.",trap:"الاعتماد على قاعدة اقلب واضرب دون فهم المعنى.",quick_method:"حوّل القسمة إلى سؤال: كم مجموعة؟"},
  {id:"q10",skill_id:"pedagogy",difficulty:"متقدم",is_diagnostic:true,priority:91,title:"الفهم العلاقي للمساواة",question_text:"أي سؤال يقيس الفهم العلاقي لعلامة المساواة بصورة أفضل؟",options:["احسب ٨+٤","اكتب ناتج ١٢−٥","ضع عددًا في □ ليصبح ٨+٤ = □+٥ صحيحًا، واشرح","أكمل جدول الجمع"],correct_index:2,explanation:"يقيس تكافؤ الطرفين لا مجرد تنفيذ عملية وكتابة الناتج.",trap:"اختيار سؤال إجرائي لا يكشف معنى المساواة.",quick_method:"اختر مهمة تتطلب موازنة طرفين وتفسيرًا."},

  {id:"q11",skill_id:"numbers",difficulty:"متقدم",is_diagnostic:false,priority:90,title:"تحويل عدد عشري",question_text:"ما أبسط صورة للكسر المكافئ للعدد ٠٫٣٧٥؟",options:["٣⁄٥","٣⁄٨","٣٧⁄١٠٠","٥⁄٨"],correct_index:1,explanation:"٠٫٣٧٥=٣٧٥⁄١٠٠٠، وبالقسمة على ١٢٥ نحصل على ٣⁄٨.",trap:"حذف الأصفار دون تبسيط صحيح.",quick_method:"اكتب العدد على قوة ١٠ ثم اختصر."},
  {id:"q12",skill_id:"numbers",difficulty:"متقدم",is_diagnostic:false,priority:89,title:"القاسم المشترك في سياق",question_text:"لدى معلم ٤٨ بطاقة حمراء و٦٠ زرقاء ويريد أكبر عدد من الحزم المتماثلة دون بقايا. كم حزمة؟",options:["٦","١٠","١٢","٢٤"],correct_index:2,explanation:"أكبر عدد للحزم هو ق.م.أ(٤٨،٦٠)=١٢.",trap:"اختيار المضاعف المشترك بدل القاسم المشترك.",quick_method:"عبارة أكبر عدد من مجموعات متساوية تشير إلى ق.م.أ."},
  {id:"q13",skill_id:"numbers",difficulty:"متوسط",is_diagnostic:false,priority:88,title:"تفسير الباقي",question_text:"ينتقل ١٥٧ متعلمًا في حافلات تسع كل واحدة ٢٤. ما أقل عدد من الحافلات؟",options:["٦","٧","٨","٦ والباقي ١٣"],correct_index:1,explanation:"١٥٧÷٢٤=٦ والباقي ١٣، لذا نحتاج حافلة سابعة.",trap:"ترك الباقي دون تفسير في السياق.",quick_method:"إذا بقي أشخاص فقرّب عدد الحافلات إلى الأعلى."},
  {id:"q14",skill_id:"algebra",difficulty:"متقدم",is_diagnostic:false,priority:90,title:"قاعدة دالة من جدول",question_text:"قيم س: −١، ٠، ١، ٢ وتقابلها ص: ٥، ٣، ١، −١. ما قاعدة الدالة؟",options:["ص=٢س+٣","ص=−٢س+٣","ص=−٢س+٥","ص=٣س−٢"],correct_index:1,explanation:"الميل −٢، والمقطع عند س=٠ يساوي ٣.",trap:"استخدام أول قيمة ص بوصفها المقطع دون الرجوع إلى س=٠.",quick_method:"استخرج معدل التغير ثم قيمة ص عند س=٠."},
  {id:"q15",skill_id:"algebra",difficulty:"متقدم",is_diagnostic:false,priority:88,title:"عكس علاقة خطية",question_text:"إذا كانت ص=٣س+٤، فأي عبارة صحيحة لس بدلالة ص؟",options:["س=(ص+٤)⁄٣","س=٣ص−٤","س=(ص−٤)⁄٣","س=ص⁄٣−٤"],correct_index:2,explanation:"نطرح ٤ ثم نقسم على ٣: س=(ص−٤)⁄٣.",trap:"عكس العمليات دون المحافظة على ترتيبها.",quick_method:"اعزل المتغير بعكس العمليات من الخارج إلى الداخل."},
  {id:"q16",skill_id:"proportion",difficulty:"متقدم",is_diagnostic:false,priority:91,title:"زيادتان متعاكستان",question_text:"زاد سعر منتج ٢٠٪ ثم انخفض السعر الجديد ٢٠٪. ما التغير الكلي؟",options:["عاد للأصل","انخفض ٤٪","زاد ٤٪","انخفض ٢٠٪"],correct_index:1,explanation:"من ١٠٠ إلى ١٢٠ ثم ينقص ٢٤ فيصبح ٩٦؛ انخفاض ٤٪.",trap:"جمع +٢٠٪ و−٢٠٪ على أساس واحد.",quick_method:"استخدم قيمة افتراضية ١٠٠."},
  {id:"q17",skill_id:"proportion",difficulty:"متوسط",is_diagnostic:false,priority:86,title:"مقياس الرسم",question_text:"مخطط بمقياس ١:٥٠ يظهر جدارًا طوله ٨ سم. ما طوله الحقيقي؟",options:["٤٠ سم","٤ م","٤٠ م","٤٠٠ م"],correct_index:1,explanation:"٨×٥٠=٤٠٠ سم=٤ م.",trap:"نسيان تحويل السنتيمتر إلى متر.",quick_method:"اضرب بالمقياس ثم وحّد الوحدة."},
  {id:"q18",skill_id:"geometry",difficulty:"متوسط",is_diagnostic:false,priority:87,title:"الزاوية الخارجية",question_text:"زاويتان داخليتان بعيدتان عن زاوية خارجية في مثلث قياسهما ٤٨° و٦٧°. ما قياس الزاوية الخارجية؟",options:["٦٧°","١٠٥°","١١٥°","١٨٠°"],correct_index:2,explanation:"الزاوية الخارجية تساوي مجموع الزاويتين الداخليتين البعيدتين: ١١٥°.",trap:"طرح المجموع من ١٨٠ بلا حاجة.",quick_method:"الخارجية = مجموع الداخليتين البعيدتين."},
  {id:"q19",skill_id:"geometry",difficulty:"متقدم",is_diagnostic:false,priority:85,title:"خصائص الدوران",question_text:"أي خاصية لا يلزم أن تبقى ثابتة بعد دوران شكل ٩٠°؟",options:["الأطوال","قياسات الزوايا","المساحة","الاتجاه بالنسبة للمحاور"],correct_index:3,explanation:"الدوران يحفظ التطابق لكنه يغير الاتجاه والموقع غالبًا.",trap:"الخلط بين خصائص الشكل وموضعه.",quick_method:"التحويلات المتطابقة تحفظ القياس لا الاتجاه المطلق."},
  {id:"q20",skill_id:"measurement",difficulty:"متقدم",is_diagnostic:false,priority:89,title:"حجم منشور عشري",question_text:"صندوق أبعاده ٢٫٥م، ١٫٢م، ٠٫٨م. ما حجمه؟",options:["٢٫٤ م³","٣٫٠ م³","٤٫٥ م³","٢٤ م³"],correct_index:0,explanation:"٢٫٥×١٫٢×٠٫٨=٢٫٤ م³.",trap:"إهمال الوحدة المكعبة أو موضع الفاصلة.",quick_method:"اجمع ضرب عددين سهلين أولًا: ٢٫٥×١٫٢=٣."},
  {id:"q21",skill_id:"measurement",difficulty:"متقدم",is_diagnostic:false,priority:87,title:"المحيط الثابت",question_text:"أي مستطيل محيطه ٢٤ وحدة يحقق أكبر مساحة؟",options:["١×١١","٣×٩","٥×٧","٦×٦"],correct_index:3,explanation:"عند ثبات المحيط تكون المساحة العظمى للمربع: ٦×٦=٣٦.",trap:"الاعتقاد أن زيادة أحد البعدين تزيد المساحة دائمًا.",quick_method:"مع مجموع ثابت، يتعاظم الضرب عند تقارب العددين."},
  {id:"q22",skill_id:"statistics",difficulty:"متقدم",is_diagnostic:false,priority:90,title:"القيمة المتطرفة",question_text:"للبيانات ٤،٥،٦،٦،٧،٨،٣٠؛ أي مقياس يصف المركز أفضل؟",options:["المتوسط","الوسيط","المدى","الانحراف المعياري"],correct_index:1,explanation:"الوسيط ٦ أقل تأثرًا بالقيمة المتطرفة ٣٠.",trap:"اختيار المتوسط تلقائيًا لكل مجموعة بيانات.",quick_method:"عند وجود قيمة متطرفة قارن المتوسط بالوسيط."},
  {id:"q23",skill_id:"statistics",difficulty:"متقدم",is_diagnostic:false,priority:88,title:"تحيز العينة",question_text:"سأل مسؤول عن رضا المقصف الطلاب الذين اشتروا منه فقط. ما نوع المشكلة؟",options:["حجم العينة كبير","العينة متحيزة","لا يمكن حساب المتوسط","السؤال مفتوح"],correct_index:1,explanation:"استبعد من لم يشتروا وربما كانوا الأقل رضا.",trap:"اعتبار كثرة المشاركين كافية لضمان التمثيل.",quick_method:"اسأل: من لم تتح له فرصة الدخول في العينة؟"},
  {id:"q24",skill_id:"pedagogy",difficulty:"متقدم",is_diagnostic:false,priority:95,title:"المحيط والمساحة",question_text:"يعتقد متعلم أن الأشكال ذات المحيط نفسه لها المساحة نفسها. ما النشاط الأقوى؟",options:["إعطاؤه القاعدة للحفظ","تكوين مستطيلات مختلفة بخيط ثابت وحساب مساحاتها","تكليفه بحل عشر مسائل مباشرة","عرض تعريف المحيط فقط"],correct_index:1,explanation:"التجربة بمحيط ثابت ومساحات مختلفة تكشف التصور الخاطئ بصريًا وعدديًا.",trap:"تصحيح الإجابة دون معالجة الفكرة الأصلية.",quick_method:"اختر نشاطًا يولّد مثالًا مضادًا محسوسًا."},
  {id:"q25",skill_id:"pedagogy",difficulty:"متقدم",is_diagnostic:false,priority:93,title:"التقويم التكويني",question_text:"بعد شرح مفهوم التناسب، أي إجراء يقدم دليلًا أسرع على فهم جميع المتعلمين؟",options:["سؤال شفهي لمتعلم واحد","واجب منزلي طويل","بطاقة خروج بسؤال يطلب التبرير","إعادة الشرح بالطريقة نفسها"],correct_index:2,explanation:"بطاقة الخروج تجمع دليلًا فرديًا سريعًا ويمكن تحليل أنماط الإجابات.",trap:"الاعتماد على إجابة طالب واحد لتمثيل الصف.",quick_method:"اختر أداة قصيرة فردية تكشف التفكير."},
  {id:"q26",skill_id:"pedagogy",difficulty:"متقدم",is_diagnostic:false,priority:92,title:"اختيار التمثيل",question_text:"أي تمثيل أنسب لبدء تعليم ضرب كسر في عدد صحيح؟",options:["قاعدة اضرب البسط فقط","نموذج مجموعات متكررة أو شريط كسري","آلة حاسبة","حفظ أمثلة محلولة"],correct_index:1,explanation:"النموذج يربط الضرب بالجمع المتكرر ويُظهر معنى الناتج.",trap:"بدء التعليم بالخوارزمية قبل المعنى.",quick_method:"ابدأ بتمثيل يكشف بنية العملية."}
];

export const courses = [
  {id:"c01",title:"الرخصة المهنية رياضيات ١ — أ. خالد عزمي",provider:"منصة ثقة التعليمية",trainer:"خالد عزمي",skill_id:null,level:"رياضيات ١",description:"دورة خارجية لمعلمي ومعلمات المرحلة الابتدائية، ويُراجع المحتوى والمواعيد والأسعار في المصدر مباشرة.",url:"https://thiqa.net/10",telegram_url:"https://t.me/mathematics_khaled",featured:true,active:true},
  {id:"c02",title:"العدد والعمليات بعمق مفاهيمي",provider:"مسار مقترح داخل الملتقى",trainer:"فريق المحتوى",skill_id:"numbers",level:"متوسط–متقدم",description:"الكسور والقيمة المنزلية والقواسم وتفسير الباقي وتحليل الأخطاء.",url:"",telegram_url:"",featured:false,active:true},
  {id:"c03",title:"الجبر والأنماط والاستدلال",provider:"مسار مقترح داخل الملتقى",trainer:"فريق المحتوى",skill_id:"algebra",level:"متوسط–متقدم",description:"الحد النوني والتكافؤ والعلاقات الخطية والتمثيلات المتعددة.",url:"",telegram_url:"",featured:false,active:true},
  {id:"c04",title:"الهندسة والقياس",provider:"مسار مقترح داخل الملتقى",trainer:"فريق المحتوى",skill_id:"geometry",level:"متوسط–متقدم",description:"التحويلات وعامل القياس والمحيط والمساحة والحجم.",url:"",telegram_url:"",featured:false,active:true},
  {id:"c05",title:"المعرفة التربوية الرياضية",provider:"مسار مقترح داخل الملتقى",trainer:"فريق المحتوى",skill_id:"pedagogy",level:"مهني",description:"تحليل أخطاء المتعلمين واختيار التمثيلات والتقويم التكويني.",url:"",telegram_url:"",featured:true,active:true}
];

export const announcements = [
  {id:"a01",title:"مرحبًا بكم في بوصلة رياضيات ١",body:"ابدؤوا بالتشخيص، ثم أرسلوا احتياجاتكم ليتم بناء الخطة الأسبوعية وفق البيانات.",active:true,created_at:new Date().toISOString()},
  {id:"a02",title:"قناة المدرب خالد عزمي",body:"أضيف رابط القناة ورابط دورة رياضيات ١ إلى قسم الدورات.",active:true,created_at:new Date().toISOString()}
];
